package com.example.client.ultils;

public enum Request {
    LOGIN,
    LOGOUT,
    UPDATE_PROFILE,
    NUMBER_FRIEND,
    NUMBER_FRIEND_SUGGESTION,
    USER_INFO,
    UNFRIEND,
    SEND_FRIEND_REQUEST,
    NUMBER_FRIEND_REQUEST,
    ACCEPT_REQUEST,
    DENIED_REQUEST,
}
